### ISSUE TITLE
Update dependency NX 0.7

### ISSUE THREAD

**Issue by ndrean** [mickel8/xav#4]

**Comment by mickel8** [comment]
Hi @ndrean, would you like to submit a PR?

**Comment by ndrean** [comment]
@mickel8 

I have in my Mix:
```elixir
{:xav, "~> 0.3.0"},
{:nx, "~> 0.7"},
{:bumblebee, "~>0.5"},
```

I start a fresh mix deps.get (and erased mix.lock, /deps, /_build ...), but I have a depency resolution pb... 🤯


```
Because xav >= 0.2.0 depends on nx ~> 0.6.0 and your app depends on nx ~> 0.7, xav >= 0.2.0 is forbidden.
So, because your app depends on xav ~> 0.3.0, version solving failed.
```

**Comment by mickel8** [comment]
You have to lock xav to master, I haven't released your PR yet. ffmpeg-version is not actually used :)
